Feature/Extended flip for option weights.
UWCS/apollo pull request #141
Opened 2022-12-31 22:19 UTC by KarlKennerley

Closes issue #139.

Added the ability to add weights to provided options passed as arguments. The keyword "weights" separates the options and weights in the supplied arguments. The number of options must match the number of weights.

2023-01-01 21:58 UTC, Joeyh021 commented
Hey, thanks for the PR! Can you provide a quick screenshot demoing this, and check the CI failures too. Happy to merge otherwise, implementation seems solid.

2023-01-02 14:14 UTC, KarlKennerley commented
> Hey, thanks for the PR! Can you provide a quick screenshot demoing this, and check the CI failures too. Happy to merge otherwise, implementation seems solid.

See attached. I've made a further change to the file and will look at the CI now.

![Options Weighted](https://user-images.githubusercontent.com/58265182/210187015-62a4edd8-a319-46be-9232-35515981aeda.png)
![Unmatched Options   Weights](https://user-images.githubusercontent.com/58265182/210187016-bbbda86c-337e-4324-8ef6-b2d6d02ef724.png)

2023-01-02 14:18 UTC, ericthelemur commented
Looking good. I would recommend moving "weights" index into a separate variable. That would most likely fix some of Black's formatting problem. The issue it comes up with about remove logging.py is not cause by your code, so ignore that error for now.

2023-01-02 17:42 UTC, Joeyh021 commented
LGTM

2023-01-02 18:15 UTC, ericthelemur requested changes
I've got a couple of suggestions. Moving `options` outside the if makes it a little clearer imo, but everything else is very minor.

(To commit the changes, go to the Files tab, click `Add suggestion to batch` for any you agree with and commit from there)

2023-01-02 18:15 UTC, ericthelemur commented on cogs/commands/flip.py
> +                f"{display_name}:({random.choices(options, weights=option_weights, k=1)[0] if weighted else {random.choice(options)}.lstrip('@')}"
```suggestion
                f"{display_name}: {(random.choices(options, weights=option_weights, k=1)[0] if weighted else {random.choice(options)}).lstrip('@')}"
```
There was a stray bracket after the colon, and moved `lstrip outside the if-else`

2023-01-02 18:15 UTC, ericthelemur commented on cogs/commands/flip.py
> +                else:
```suggestion
                weighted = True
                options = args[:weight_index]
                option_weights = [int(weight) for weight in args[weight_index + 1 :]]
                if len(options) != len(option_weights):
```
I think moving `options` and `options_weights` outside the if statement make the control flow a little clearer. Also there is a stray colon inserted on the RHS of the original condition.

2023-01-02 19:59 UTC, ericthelemur commented
Looks good. I'll give it a final test tonight, then I'll merge. TY

2023-01-03 00:28 UTC, ericthelemur commented on cogs/commands/flip.py
> +                f"{display_name}: {(random.choices(options, weights=option_weights, k=1)[0] if weighted else {random.choice(options)}).lstrip('@')}"
```suggestion
                f"{display_name}: {(random.choices(options, weights=option_weights, k=1)[0] if weighted else random.choice(options)).lstrip('@')}"
```

2023-01-03 00:31 UTC, ericthelemur approved these changes

2023-01-03 00:31 UTC, merged